# Generated by Django 5.2.11 on 2026-03-10 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube')], max_length=50, null=True, verbose_name='Platform')),
                ('content', models.TextField(verbose_name='Initial Content Idea / Input')),
                ('visual_idea', models.TextField(blank=True, null=True, verbose_name='Visual Idea / Prompt')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating_content', 'Generating Content'), ('content_generated', 'Content Generated'), ('ready_to_publish', 'Ready to Publish'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social_accounts.usersocialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(default='text_and_hashtags', max_length=50, verbose_name='Content Type')),
                ('generated_text', models.TextField(verbose_name='Generated Text / Caption')),
                ('suggested_hashtags', models.TextField(blank=True, null=True, verbose_name='Suggested Hashtags')),
                ('suggested_publish_time', models.DateTimeField(blank=True, null=True, verbose_name='Suggested Publish Time')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('avatar_video_url', models.URLField(blank=True, null=True, verbose_name='Avatar Video URL')),
                ('audio_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Audio File Path')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_content', to='content_generator.post')),
            ],
        ),
    ]
