# Generated by Django 5.2.11 on 2026-09-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generator', '0002_phase1_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='content_type',
            field=models.CharField(choices=[('text_and_hashtags', 'Text and hashtags'), ('caption', 'Caption'), ('thread', 'Thread'), ('youtube_metadata', 'YouTube metadata')], default='text_and_hashtags', max_length=100, verbose_name='Content Type'),
        ),
    ]
