# Generated by Django 5.2.11 on 2026-09-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_generator', '0003_alter_generatedcontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='content_type',
            field=models.CharField(choices=[('text_and_hashtags', 'Text and hashtags'), ('text', 'Text'), ('image_description', 'Image description'), ('caption', 'Caption'), ('thread', 'Thread'), ('youtube_metadata', 'YouTube metadata')], default='text_and_hashtags', max_length=100, verbose_name='Content Type'),
        ),
    ]
